feat: test Workflow
utopia-php/ab pull request #12
Opened 2023-08-02 05:23 UTC by 2002Bishwajeet

Fixes [#103](https://github.com/utopia-php/framework/issues/103)

2023-08-03 01:53 UTC, lohanidamodar requested changes
@2002Bishwajeet Let's also remove the travis config

2023-08-11 23:28 UTC, abnegate commented on .github/workflows/test.yml
> +              uses: shivammathur/setup-php@2.25.5
Let's use docker following the workflow [here](https://github.com/utopia-php/database/blob/main/.github/workflows/tests.yml) so we don't need to use third-party actions

2023-08-15 02:09 UTC, abnegate commented on .github/workflows/test.yml
> +on: [pull_request]
Let's add on push to main as well, so merge commits are tested

2023-10-11 06:26 UTC, lohanidamodar approved these changes

2023-10-11 06:27 UTC, merged